name = "zufrieden 002"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "https://github.com/zufrieden/zufrieden.github.com/blob/master/LICENSE.txt"
description = "Theme for my personal website version 2"
homepage = "https://github.com/zufrieden/zufrieden.github.com"
tags = ["clean", "simple", "blog", "portfolio", "flexbox", "css grid", "minimalist", "responsive"]
features = ["responsive"]
min_version = "0.30"

[author]
  name = "Marc Friederich"
  homepage = "http://zufrieden.io"
